# Generated by Django 5.1.5 on 2025-01-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('condition', models.TextField(verbose_name='Medical Condition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Medication Name')),
                ('dose', models.CharField(help_text='e.g., 500mg', max_length=50, verbose_name='Dose')),
                ('frequency', models.CharField(choices=[('once', 'Once a day'), ('twice', 'Twice a day'), ('thrice', 'Thrice a day')], max_length=10, verbose_name='Frequency')),
                ('time', models.TimeField(help_text='Time to take the medication', verbose_name='Time')),
                ('health_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='elder_care_management.healthrecord', verbose_name='Health Record')),
            ],
        ),
    ]
